password_reset/urls.py
from django.conf.urls import url
from . import views

app_name = 'password_reset'
urlpatterns = [


    url(r'^recover/(?P<signature>.+)/$', views.recover_done, name='password_reset_sent'),
    url(r'^recover/$', views.recover, name='password_reset_recover'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_done'),
    url(r'^reset/(?P<token>[\w:-]+)/$', views.reset, name='password_reset_reset'),
    # url(r'^password_change/(?P<user_id>[0-9]+)', views.password_change, name='password_change'),

]

tpo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('api/', include('tpo_drf.urls')),
    # path('password/', include('password_reset.urls', namespace='password_reset')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

password_reset/forms.py
from django import forms
from django.core.validators import validate_email
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import User

from .utils import get_user_model


class PasswordRecoveryForm(forms.Form):
   # username_or_email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','type':'text','placeholder': 'Email id'}))
    username_or_email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    error_messages = {
        'not_found': _("Sorry, this user doesn't exist."),
    }

    def __init__(self, *args, **kwargs):
        self.case_sensitive = kwargs.pop('case_sensitive', True)
        search_fields = kwargs.pop('search_fields', ('username', 'email'))
        super(PasswordRecoveryForm, self).__init__(*args, **kwargs)

        message = ("No other fields than username and email are supported "
                   "by default")
        if len(search_fields) not in (1, 2):
            raise ValueError(message)
        for field in search_fields:
            if field not in ['username', 'email']:
                raise ValueError(message)

        labels = {
            'username': _('Username'),
            'email': _('Email'),
            'both': _(''),
        }
        User = get_user_model()  # noqa
        if getattr(User, 'USERNAME_FIELD', 'username') == 'email':
            self.label_key = 'email'
        elif len(search_fields) == 1:
            self.label_key = search_fields[0]
        else:
            self.label_key = 'both'
        self.fields['username_or_email'].label = labels[self.label_key]

    def clean_username_or_email(self):
        username = self.cleaned_data['username_or_email']
        cleaner = getattr(self, 'get_user_by_%s' % self.label_key)
        self.cleaned_data['user'] = user = cleaner(username)

        user_is_active = getattr(user, 'is_active', True)
        recovery_only_active_users = getattr(settings,
                                             'RECOVER_ONLY_ACTIVE_USERS',
                                             False)

        if recovery_only_active_users and not user_is_active:
            raise forms.ValidationError(_("Sorry, inactive users can't "
                                        "recover their password."))

        return username

    def get_user_by_username(self, username):
        key = 'username__%sexact' % ('' if self.case_sensitive else 'i')
        User = get_user_model()
        try:
            user = User._default_manager.get(**{key: username})
        except User.DoesNotExist:
            raise forms.ValidationError(self.error_messages['not_found'],
                                        code='not_found')
        return user

    def get_user_by_email(self, email):
        validate_email(email)
        key = 'email__%sexact' % ('' if self.case_sensitive else 'i')
        User = get_user_model()
        try:
            user = User._default_manager.get(**{key: email})
        except User.DoesNotExist:
            raise forms.ValidationError(self.error_messages['not_found'],
                                        code='not_found')
        return user

    def get_user_by_both(self, username):
        key = '__%sexact'
        key = key % '' if self.case_sensitive else key % 'i'

        def f(field):
            return Q(**{field + key: username})
        filters = f('username') | f('email')
        User = get_user_model()
        try:
            user = User._default_manager.get(filters)
        except User.DoesNotExist:
            raise forms.ValidationError(self.error_messages['not_found'],
                                        code='not_found')
        except User.MultipleObjectsReturned:
            raise forms.ValidationError(_("Unable to find user."))

        return user


class PasswordResetForm(forms.Form):
    password1 = forms.CharField(
        label=_('New password'),
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'New Password','id':'pwd1'}),
    )
    password2 = forms.CharField(
        label=_('New password (confirm)'),
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirm Password', 'id':'pwd2'}),
    )

    error_messages = {
        'password_mismatch': _("The two passwords didn't match."),
    }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PasswordResetForm, self).__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1', '')
        password2 = self.cleaned_data['password2']
        if not password1 == password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch')
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['password1'])
        if commit:
            get_user_model()._default_manager.filter(pk=self.user.pk).update(
                password=self.user.password,
            )
        return self.user
    
class PasswordChangeForm(forms.ModelForm):
    oldPassword=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','type':'password','placeholder':'oldpassword'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','type':'password','placeholder':'New Password'}))
    confirm_pass = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','type':'password','placeholder':'Confirm Password'}))
    class Meta:
        model = User
        fields = ('oldPassword','new_password','confirm_pass')

password_reset/views.py
from django.conf import settings
from django.core import signing
from django.core.mail import send_mail
from django.urls import reverse, reverse_lazy

from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.debug import sensitive_post_parameters

try:
    from django.contrib.sites.shortcuts import get_current_site
except ImportError:
    from django.contrib.sites.models import get_current_site
from .forms import PasswordRecoveryForm, PasswordResetForm
from .signals import user_recovers_password
from .utils import get_user_model, get_username
from django.template.loader import render_to_string
import logging

logger = logging.getLogger('promotion')
logger.addHandler(logging.NullHandler())


class SaltMixin(object):
    salt = 'password_recovery'
    url_salt = 'password_recovery_url'


def loads_with_timestamp(value, salt):
    """Returns the unsigned value along with its timestamp, the time when it
    got dumped."""
    try:
        signing.loads(value, salt=salt, max_age=-999999)
    except signing.SignatureExpired as e:
        age = float(str(e).split('Signature age ')[1].split(' >')[0])
        timestamp = timezone.now()
        return timestamp, signing.loads(value, salt=salt)


class RecoverDone(SaltMixin, generic.TemplateView):
    logger.debug("start of recovery done view")
    template_name = 'password_reset/MFS_Reset_Sent.html'

    def get_context_data(self, **kwargs):
        ctx = super(RecoverDone, self).get_context_data(**kwargs)
        try:
            global email_field

            ctx['timestamp'], ctx['email'] = loads_with_timestamp(
                self.kwargs['signature'], salt=self.url_salt
            )

            ctx['email'] = email_field[0]
        except signing.BadSignature:
            raise Http404
        return ctx


recover_done = RecoverDone.as_view()

email_field = ""


class Recover(SaltMixin, generic.FormView):
    logger.debug("start of recover view")
    case_sensitive = True
    form_class = PasswordRecoveryForm
    template_name = 'password_reset/MFS_Recovery_Form.html'
    success_url_name = 'password_reset:password_reset_sent'
    email_template_name = 'password_reset/recovery_email.txt'
    email_subject_template_name = 'password_reset/recovery_email_subject.txt'
    search_fields = ['username', 'email']

    def get_success_url(self):
        return reverse(self.success_url_name, args=[self.mail_signature])

    def get_context_data(self, **kwargs):
        kwargs['url'] = self.request.get_full_path()
        return super(Recover, self).get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super(Recover, self).get_form_kwargs()
        kwargs.update({
            'case_sensitive': self.case_sensitive,
            'search_fields': self.search_fields,
        })
        return kwargs

    def get_site(self):
        return get_current_site(self.request)

    def send_notification(self):
        context = {
            'site': self.get_site(),
            'user': self.user,
            'username': get_username(self.user),
            'token': signing.dumps(self.user.pk, salt=self.salt),
            'secure': self.request.is_secure(),
        }
        h = self.get_site()

        data = {}

        subject = 'TPO WebApp Login Password Recovery'
        html_content = render_to_string('password_reset/MFS_password_recovery_email.html', context)
        to = [self.user.email]

        global email_field

        # This variable will be access from RecoverDone class to get sender emlai
        email_field = [self.user.email]
        #         print "mail to",str(email_field)
        from_email = settings.EMAIL_HOST_USER
        #         print "mail from",from_email
        send_mail(subject, "", from_email, to, fail_silently=True, html_message=html_content)
        # print "mail",send_mail(subject,"",from_email,to,fail_silently=True, html_message=html_content)

    def form_valid(self, form):
        self.user = form.cleaned_data['user']
        self.send_notification()
        if (
                len(self.search_fields) == 1 and
                self.search_fields[0] == 'username'
        ):
            # if we only search by username, don't disclose the user email
            # since it may now be public information.
            email = self.user.username
        else:
            email = self.user.email
        self.mail_signature = signing.dumps(email, salt=self.url_salt)
        return super(Recover, self).form_valid(form)


recover = Recover.as_view()


class Reset(SaltMixin, generic.FormView):
    logger.debug("start of reset view")
    form_class = PasswordResetForm
    token_expires = None
    template_name = 'password_reset/MFS_Password_Reset.html'
    success_url = reverse_lazy('password_reset:password_reset_done')

    def get_token_expires(self):
        duration = getattr(settings, 'PASSWORD_RESET_TOKEN_EXPIRES',
                           self.token_expires)
        if duration is None:
            duration = 3600 * 48  # Two days
        return duration

    @method_decorator(sensitive_post_parameters('password1', 'password2'))
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        self.user = None

        try:
            pk = signing.loads(kwargs['token'],
                               max_age=self.get_token_expires(),
                               salt=self.salt)
        except signing.BadSignature:
            return self.invalid()

        self.user = get_object_or_404(get_user_model(), pk=pk)
        return super(Reset, self).dispatch(request, *args, **kwargs)

    def invalid(self):
        return self.render_to_response(self.get_context_data(invalid=True))

    def get_form_kwargs(self):
        kwargs = super(Reset, self).get_form_kwargs()
        kwargs['user'] = self.user
        return kwargs

    def get_context_data(self, **kwargs):
        ctx = super(Reset, self).get_context_data(**kwargs)
        if 'invalid' not in ctx:
            ctx.update({
                'username': get_username(self.user),
                'token': self.kwargs['token'],
            })
        return ctx

    def form_valid(self, form):
        form.save()
        user_recovers_password.send(
            sender=get_user_model(),
            user=form.user,
            request=self.request
        )
        return redirect(self.get_success_url())


reset = Reset.as_view()


class ResetDone(generic.TemplateView):
    logger.debug("start of reset done view")
    template_name = 'password_reset/MFS_Recovery_Done.html'


reset_done = ResetDone.as_view()

# def password_change(request,user_id):
# #     logger.debug("start of password change view")
#     try:
#         print("INNNNNNNNN")
#         server1 = get_object_or_404(User, pk=user_id)
#         group=Group.objects.get(user=server1)
#
#         if request.method == "POST":
# #             logger.debug(" password change post method")
#             print("dddd")
#             form = PasswordChangeForm(request.POST)
#             if form.is_valid():
# #                 logger.debug("password change form is valid")
#                 user1 = authenticate(username =server1, password=form.cleaned_data['oldPassword'])
#                 if user1 is not None:
# #                    logger.debug("password change form is valid")
#
#                    user1.password=form.cleaned_data['new_password']
#                    user1.set_password(user1.password)
#                    user1.save()
#                    auth_login(request, user1)
#
#
#                    if group.name=="Club":
#                        variables = RequestContext(request,
#                                        {'group':group, 'updatepassword':PasswordChangeForm,'context2': "Your Password has been updated"})
#                        return render(request, 'registration/updateDetails.html', variables)
#
#                 else:
#
#                     variables = RequestContext(request,
#                                        {'group': group, 'updatepassword':PasswordChangeForm,'context2': "Invalid Password"})
#                     if group.name=="Club":
#                        return render(request, 'registration/updateDetails.html', variables)
#
#
#             else:
#
#                 variables = RequestContext(request,
#                                        {'group':group,'updatepassword':PasswordChangeForm,})
#                 if group.name=="Club":
#                        return render(request, 'registration/updateDetails.html', variables)
#
#         else:
#
#             print("get")
#             variables = RequestContext(request,
#                                    {'group':group, 'updatepassword':PasswordChangeForm})
#             if group.name=="Club":
#                    return render(request,'registration/updateDetails.html', variables)
#
#
#     except Exception as e:
#         print(e)
#         render(request,'password_reset/404.html')

password_reset/templates/password_reset/MFS_Password_Reset.html
{% load static from staticfiles %}
{% load i18n %}
{%block head%}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>TPO | Forgot Password</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- <link rel="icon" type="image/png" href="{% static 'Password_Reset/images/icons/favicon.ico' %}"/> -->
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset//vendor/bootstrap/css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset//fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/fonts/iconic/css/material-design-iconic-font.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/animate/animate.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/css-hamburgers/hamburgers.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/animsition/css/animsition.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/select2/select2.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/daterangepicker/daterangepicker.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/css/util.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/css/main.css' %}">
		<script src="{% static 'Password_Reset/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
		<script src="{% static 'Password_Reset/vendor/animsition/js/animsition.min.js' %}"></script>
		<script src="{% static 'Password_Reset/vendor/bootstrap/js/popper.js' %}"></script>
		<script src="{% static 'Password_Reset/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'Password_Reset/vendor/select2/select2.min.js' %}"></script>
		<script src="{% static 'Password_Reset/vendor/daterangepicker/moment.min.js' %}"></script>
		<script src="{% static 'Password_Reset/vendor/daterangepicker/daterangepicker.js' %}"></script>
		<script src="{% static 'Password_Reset/vendor/countdowntime/countdowntime.js' %}"></script>
		<script src="{% static 'Password_Reset/js/main.js' %}"></script>
	</head>
	{%endblock%}
	{% block content %}
		<body>
			
			<div class="limiter">
				<div class="container-login100">
					<div class="wrap-login100">
						<center>
						<form method="post" action="#"  class="login100-form validate-form" role="form">
							<span class="login100-form-title p-b-26">
								<a href="#" class="alert-link" style="color:#008FC8;font-size: 15px;"><center>{% blocktrans %}Hi, <strong>{{ username }}</strong>. Please choose your new password.{% endblocktrans %}</center></a>
							</span>
							<form method="post" action="{% url 'password_reset:password_reset_reset' token %}" role="form">
								{% csrf_token %}
								
								{{ form.password1 }}
								<span id="error1"style="color:red"></span>
								
								<br>
								{{ form.password2 }}
								<span id="error2"style="color:red"></span>
								<br>
								
								<div class="container-login100-form-btn">
									<div class="wrap-login100-form-btn">
										<div class="login100-form-bgbtn"></div>
										<input class="btn recover" style="background-color: Transparent;"  id="btn" type="submit" value="{% trans 'Submit' %}">
									</div>
								</div>
							</form>
						</form>
						</center>
					</div>
				</div>
			</div>
			
			<div id="dropDownSelect1"></div>
		</body>
		<script type="text/javascript">
			$(document).ready(function(){
				$('#pwd1').removeClass('form-control');
				$('#pwd1').addClass('input100');
				$('#pwd2').removeClass('form-control');
				$('#pwd2').addClass('input100');
			})
		</script>
	{% endblock %}
</html>

password_reset/templates/password_reset/MFS_Recovery_Done.html
{% load static from staticfiles %}
{% load i18n %}
{%block head%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>TPO | Forgot Password</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link rel="icon" type="image/png" href="{% static 'Password_Reset/images/icons/favicon.ico' %}"/> -->
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset//vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset//fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/fonts/iconic/css/material-design-iconic-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/animate/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/daterangepicker/daterangepicker.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/css/main.css' %}">
	<script src="{% static 'Password_Reset/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/animsition/js/animsition.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/daterangepicker/daterangepicker.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'Password_Reset/js/main.js' %}"></script>
</head>
{%endblock%}
{% block content %}

<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100" style="margin-top:-8em;">
				<center>
					<span class="login100-form-title p-b-26" style="font-size: 15px">
						 New Password set
					</span>
					<div>
						<p style="font-size:16px;">Your password has been successfully reset. You can use it right now by login to TPO Web App.</p>
					</div>
				</center>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
</body>
</script>
{% endblock %}
</html>

password_reset/templates/password_reset/MFS_Recovery_Form.html
{% load static from staticfiles %}
{% load i18n %}
{%block head%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>TPO | Forgot Password</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link rel="icon" type="image/png" href="{% static 'Password_Reset/images/icons/favicon.ico' %}"/> -->
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset//vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset//fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/fonts/iconic/css/material-design-iconic-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/animate/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/daterangepicker/daterangepicker.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/css/main.css' %}">
	<script src="{% static 'Password_Reset/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/animsition/js/animsition.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/daterangepicker/daterangepicker.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'Password_Reset/js/main.js' %}"></script>
</head>
{%endblock%}
{% block content %}

<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<center>
					<form method="post" action="#"  class="login100-form validate-form" role="form">
						<span class="login100-form-title p-b-26">
							Forgot Password
						</span>

						<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
							{% csrf_token %}
							<p class="input100">{{ form.as_p }}</p>
							<span class="focus-input100" data-placeholder="Enter your Registered Email"></span>
						</div>
						<div class="container-login100-form-btn">
							<div class="wrap-login100-form-btn">
								<div class="login100-form-bgbtn"></div>
								<input class="btn recover" style="background-color: Transparent;"  id="btn" type="submit" value="{% trans 'Recover Password' %}">
							</div>
						</div>
					</form>
				</center>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
</body>
<script type="text/javascript">
	$(document).ready(function(){
		$('#id_username_or_email').removeClass('form-control');
		$('#id_username_or_email').addClass('input100');
	})
</script>
{% endblock %}
</html>

password_reset/templates/password_reset/MFS_Reset_Sent.html
{% load static from staticfiles %}
{% load i18n %}
{%block head%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>TPO | Forgot Password</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link rel="icon" type="image/png" href="{% static 'Password_Reset/images/icons/favicon.ico' %}"/> -->
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset//vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset//fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/fonts/iconic/css/material-design-iconic-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/animate/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/vendor/daterangepicker/daterangepicker.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Password_Reset/css/main.css' %}">
	<script src="{% static 'Password_Reset/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/animsition/js/animsition.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/daterangepicker/daterangepicker.js' %}"></script>
	<script src="{% static 'Password_Reset/vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'Password_Reset/js/main.js' %}"></script>
</head>
{%endblock%}
{% block content %}

<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100" style="margin-top:-8em;">
				<center>
					<span class="login100-form-title p-b-26" style="font-size: 15px">
						Password recovery mail sent !!
					</span>
					<div>
						<p style="font-size:16px;">{% blocktrans with ago=timestamp|timesince %}An email was sent to <strong>{{ email }}</strong>. Use the link in it to set a new password.{% endblocktrans %}</p>
					</div>
				</center>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
</body>
<script type="text/javascript">
	$(document).ready(function(){
		$('#id_username_or_email').removeClass('form-control');
		$('#id_username_or_email').addClass('input100');
	})
</script>
{% endblock %}
</html>